version: '3.8'

services:
  web:
    build: .
    ports:
    - "8000:5000"
    volumes:
    - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK DEBUG=1
    command: flask run --host=0.0.0.0 --port=5000